package com.doyun.ledger;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import androidx.recyclerview.widget.DiffUtil;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.text.NumberFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class MainActivity extends Activity {
    private static final String[] LABELS={"외식","쇼핑","쿠팡","배달","기타","공과금","제외"};
    private static final String[] FILTERS={"전체","미분류","외식","쇼핑","쿠팡","배달","기타","공과금","제외"};
    private static final String[] NAV={"▦  대시보드","≡  카테고리","□  캘린더"};
    private static final int NAVY=Color.rgb(24,35,58),BLUE=Color.rgb(48,94,255),INK=Color.rgb(31,41,55),MUTED=Color.rgb(107,114,128);
    private static final int SURFACE=Color.WHITE,BG=Color.rgb(246,247,251),LINE=Color.rgb(230,233,240);
    private final List<Item> items=new ArrayList<>();
    private final TextView[] navButtons=new TextView[3],filterChips=new TextView[9],legendValues=new TextView[7];
    private final CalendarCell[] calendarCells=new CalendarCell[42];
    private LocalDate start=LocalDate.now().withDayOfMonth(1),end=LocalDate.now(),selectedDate=LocalDate.now();
    private YearMonth calendarMonth=YearMonth.now();
    private android.content.SharedPreferences saved;
    private LinearLayout root;
    private SwipePager pager;
    private int selectedCategory=-2;
    private TextView status,totalValue,totalCaption,categoryCount,monthTitle,dayTitle,dayCount;
    private DonutChartView donut;
    private TransactionAdapter recentAdapter,categoryAdapter,dayAdapter;

    static final class Item { long time;String id,body;Long amount;boolean cancelled;int category=-1; }
    private static final class CalendarCell { LinearLayout root;TextView day,amount;LocalDate date; }

    @Override public void onCreate(Bundle state){
        super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(SURFACE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        saved=getSharedPreferences("labels",MODE_PRIVATE);start=LocalDate.parse(saved.getString("ui_start",start.toString()));end=LocalDate.parse(saved.getString("ui_end",end.toString()));selectedDate=end;calendarMonth=YearMonth.from(end);
        if(state!=null){start=LocalDate.parse(state.getString("start"));end=LocalDate.parse(state.getString("end"));selectedDate=LocalDate.parse(state.getString("selectedDate"));calendarMonth=YearMonth.parse(state.getString("calendarMonth"));selectedCategory=state.getInt("category",-2);}
        root=column();root.setBackgroundColor(BG);root.setPadding(dp(18),0,dp(18),0);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(18),i.getSystemWindowInsetTop()+dp(12),dp(18),i.getSystemWindowInsetBottom());return i;});setContentView(root);
        addAppHeader();pager=new SwipePager(this);root.addView(pager,new LinearLayout.LayoutParams(-1,0,1));pager.addView(buildDashboard());pager.addView(buildCategoryPage());pager.addView(buildCalendarPage());addBottomNav();pager.setListener(this::selectNav);load();
    }

    private void addAppHeader(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);root.addView(row,lp(-1,dp(58),0,0,0,dp(4)));LinearLayout titles=column();row.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView eyebrow=label("BOOBOO CARD",10,true,MUTED);eyebrow.setLetterSpacing(.13f);titles.addView(eyebrow);titles.addView(label("우리 카드 장부",23,true,NAVY),lp(-1,-2,0,dp(3),0,0));TextView privacy=label("LOCAL",10,true,Color.rgb(44,126,91));privacy.setPadding(dp(10),dp(6),dp(10),dp(6));privacy.setBackground(round(Color.rgb(229,247,239),50));row.addView(privacy);}
    private void addBottomNav(){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);bar.setPadding(dp(5),dp(7),dp(5),dp(4));bar.setBackground(round(SURFACE,20));bar.setElevation(dp(10));root.addView(bar,lp(-1,dp(66),0,dp(5),0,0));for(int i=0;i<3;i++){final int page=i;TextView tab=label(NAV[i],12,true,MUTED);tab.setGravity(Gravity.CENTER);tab.setClickable(true);tab.setOnClickListener(v->pager.showPage(page,page>pager.getDisplayedChild()));navButtons[i]=tab;bar.addView(tab,new LinearLayout.LayoutParams(0,-1,1));}selectNav(0);}
    private void selectNav(int page){for(int i=0;i<3;i++){navButtons[i].setTextColor(i==page?BLUE:MUTED);navButtons[i].setBackground(i==page?round(Color.rgb(237,242,255),14):null);}}

    private View buildDashboard(){ScrollView scroll=scroller();LinearLayout page=column();scroll.addView(page);page.addView(periodCard(),lp(-1,-2,0,dp(6),0,dp(10)));page.addView(importButton(),lp(-1,dp(56),0,0,0,dp(10)));status=label("",12,false,Color.rgb(55,71,112));status.setLineSpacing(0,1.2f);LinearLayout statusCard=card(dp(14),Color.rgb(237,242,255),15);statusCard.addView(status);page.addView(statusCard,lp(-1,-2,0,0,0,dp(10)));page.addView(buildSummaryCard(),lp(-1,-2,0,0,0,dp(16)));page.addView(sectionHeader("최근 거래","카테고리 탭에서 전체보기"));recentAdapter=new TransactionAdapter(false);RecyclerView recent=list(recentAdapter);recent.setNestedScrollingEnabled(false);page.addView(recent,lp(-1,-2,0,dp(7),0,dp(12)));return scroll;}
    private View periodCard(){LinearLayout card=card(dp(17),SURFACE,20);card.addView(label("조회 기간",13,true,MUTED));LinearLayout row=new LinearLayout(this);card.addView(row,lp(-1,-2,0,dp(9),0,0));Button from=dateButton(start),to=dateButton(end);from.setTextColor(BLUE);to.setTextColor(Color.rgb(25,135,94));from.setOnClickListener(v->pick(true));to.setOnClickListener(v->pick(false));row.addView(dateCell("시작일",from,Color.rgb(237,242,255),BLUE),new LinearLayout.LayoutParams(0,-2,1));row.addView(new Space(this),new LinearLayout.LayoutParams(dp(9),1));row.addView(dateCell("종료일",to,Color.rgb(231,248,240),Color.rgb(25,135,94)),new LinearLayout.LayoutParams(0,-2,1));return card;}
    private Button importButton(){Button button=new Button(this);button.setAllCaps(false);button.setText("삼성카드 RCS 불러오기  →");button.setTextSize(15);button.setTypeface(null,Typeface.BOLD);button.setTextColor(Color.WHITE);button.setBackground(round(BLUE,16));button.setElevation(dp(2));button.setOnClickListener(v->{if(start.isAfter(end)){toast("시작일은 종료일보다 늦을 수 없습니다.");return;}startRcsImport();});return button;}
    private View buildSummaryCard(){
        LinearLayout card=card(dp(18),NAVY,22);card.setElevation(dp(2));card.addView(label("실제 카드값",12,true,Color.rgb(177,188,214)));totalValue=label("0원",29,true,Color.WHITE);card.addView(totalValue,lp(-1,-2,0,dp(3),0,0));totalCaption=label("",11,false,Color.rgb(177,188,214));card.addView(totalCaption,lp(-1,-2,0,dp(2),0,dp(12)));
        LinearLayout data=new LinearLayout(this);data.setGravity(Gravity.CENTER_VERTICAL);card.addView(data);donut=new DonutChartView(this);data.addView(donut,new LinearLayout.LayoutParams(dp(178),dp(178)));
        LinearLayout legend=column();legend.setPadding(dp(12),0,0,0);data.addView(legend,new LinearLayout.LayoutParams(0,-2,1));
        for(int i=0;i<7;i++){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);View dot=new View(this);dot.setBackground(round(DonutChartView.colorAt(i),50));row.addView(dot,new LinearLayout.LayoutParams(dp(9),dp(9)));TextView name=label(LABELS[i],11,i<3,Color.rgb(220,225,238));LinearLayout.LayoutParams nameParams=new LinearLayout.LayoutParams(dp(46),dp(22));nameParams.setMargins(dp(7),0,dp(4),0);row.addView(name,nameParams);legendValues[i]=label("",11,true,Color.WHITE);legendValues[i].setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(legendValues[i],new LinearLayout.LayoutParams(-2,dp(22)));legend.addView(row,new LinearLayout.LayoutParams(-1,dp(22)));}
        return card;
    }

    private View buildCategoryPage(){LinearLayout page=column();LinearLayout heading=sectionHeader("카테고리별 내역","");categoryCount=(TextView)heading.getChildAt(1);page.addView(heading,lp(-1,-2,0,dp(6),0,dp(5)));HorizontalScrollView chipScroll=new HorizontalScrollView(this);chipScroll.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chipScroll.addView(chips);for(int i=0;i<FILTERS.length;i++){final int value=i-2;TextView chip=label(FILTERS[i],12,true,INK);chip.setGravity(Gravity.CENTER);chip.setPadding(dp(15),0,dp(15),0);chip.setOnClickListener(v->selectCategory(value));filterChips[i]=chip;chips.addView(chip,lp(-2,dp(38),0,0,dp(7),0));}page.addView(chipScroll,lp(-1,dp(42),0,0,0,dp(4)));categoryAdapter=new TransactionAdapter(true);page.addView(list(categoryAdapter),new LinearLayout.LayoutParams(-1,0,1));updateFilterChips();return page;}
    private void selectCategory(int value){if(selectedCategory==value)return;selectedCategory=value;updateFilterChips();List<Item> filtered=filteredItems();categoryCount.setText(filtered.size()+"건");categoryAdapter.submit(filtered);}
    private void updateFilterChips(){for(int i=0;i<filterChips.length;i++){boolean selected=selectedCategory==i-2;filterChips[i].setTextColor(selected?Color.WHITE:INK);filterChips[i].setBackground(round(selected?BLUE:SURFACE,50));}}

    private View buildCalendarPage(){LinearLayout page=column();LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);page.addView(heading,lp(-1,dp(52),0,dp(4),0,0));TextView prev=navArrow("‹"),next=navArrow("›");monthTitle=label("",19,true,NAVY);monthTitle.setGravity(Gravity.CENTER);heading.addView(prev,lp(dp(44),dp(44),0,0,0,0));heading.addView(monthTitle,new LinearLayout.LayoutParams(0,-2,1));heading.addView(next,lp(dp(44),dp(44),0,0,0,0));prev.setOnClickListener(v->changeMonth(-1));next.setOnClickListener(v->changeMonth(1));page.addView(buildCalendarGrid(),lp(-1,-2,0,0,0,dp(10)));LinearLayout dayHeading=sectionHeader("","");dayTitle=(TextView)dayHeading.getChildAt(0);dayCount=(TextView)dayHeading.getChildAt(1);page.addView(dayHeading);dayAdapter=new TransactionAdapter(false);page.addView(list(dayAdapter),new LinearLayout.LayoutParams(-1,0,1));return page;}
    private View buildCalendarGrid(){LinearLayout card=card(dp(12),SURFACE,20);String[] weekdays={"일","월","화","수","목","금","토"};LinearLayout names=new LinearLayout(this);for(int i=0;i<7;i++){TextView name=label(weekdays[i],11,true,i==0?Color.rgb(218,76,83):i==6?BLUE:MUTED);name.setGravity(Gravity.CENTER);names.addView(name,new LinearLayout.LayoutParams(0,dp(28),1));}card.addView(names);for(int week=0;week<6;week++){LinearLayout row=new LinearLayout(this);card.addView(row);for(int d=0;d<7;d++){CalendarCell cell=new CalendarCell();cell.root=column();cell.root.setGravity(Gravity.CENTER);cell.root.setPadding(dp(2),dp(5),dp(2),dp(5));cell.day=label("",13,true,INK);cell.day.setGravity(Gravity.CENTER);cell.amount=label("",9,false,MUTED);cell.amount.setGravity(Gravity.CENTER);cell.amount.setSingleLine();cell.root.addView(cell.day);cell.root.addView(cell.amount,lp(-1,dp(18),0,dp(3),0,0));cell.root.setOnClickListener(v->{if(cell.date!=null&&YearMonth.from(cell.date).equals(calendarMonth))selectDate(cell.date);});calendarCells[week*7+d]=cell;row.addView(cell.root,new LinearLayout.LayoutParams(0,dp(58),1));}}return card;}
    private void changeMonth(int delta){calendarMonth=calendarMonth.plusMonths(delta);selectedDate=calendarMonth.atDay(1);updateCalendar();updateDayList();}
    private void selectDate(LocalDate date){if(date.equals(selectedDate))return;LocalDate old=selectedDate;selectedDate=date;updateCalendarCell(old);updateCalendarCell(date);updateDayList();}

    private void load(){ZoneId zone=ZoneId.of("Asia/Seoul");long from=start.atStartOfDay(zone).toInstant().toEpochMilli(),until=end.plusDays(1).atStartOfDay(zone).toInstant().toEpochMilli();List<Item> loaded;try(RcsStore store=new RcsStore(this)){loaded=store.read(from,until,saved);}items.clear();items.addAll(loaded);updateAllData();}
    private void updateAllData(){String result=getSharedPreferences("rcs_import",0).getString("status","불러오기를 누르면 삼성카드 대화에서 내역을 수집합니다.");status.setText("●   "+result+"\n     "+start+" ~ "+end+" · "+items.size()+"건");updateSummary();recentAdapter.submit(new ArrayList<>(items.subList(0,Math.min(items.size(),4))));List<Item> filtered=filteredItems();categoryCount.setText(filtered.size()+"건");categoryAdapter.submit(filtered);updateFilterChips();updateCalendar();updateDayList();}
    private void updateSummary(){long[] totals=totals();long all=0;for(Item item:items)if(item.amount!=null)all+=SmsParser.signed(item.amount,item.cancelled);long actual=all-totals[6];totalValue.setText(money(actual));totalCaption.setText("총 카드값 "+money(all)+" · 제외 "+money(totals[6])+" · "+items.size()+"건");donut.setValues(totals);for(int i=0;i<7;i++)legendValues[i].setText(money(totals[i]));}
    private void updateCalendar(){monthTitle.setText(calendarMonth.format(DateTimeFormatter.ofPattern("yyyy년 M월")));LocalDate first=calendarMonth.atDay(1),cursor=first.minusDays(first.getDayOfWeek().getValue()%7);for(CalendarCell cell:calendarCells){cell.date=cursor;bindCalendarCell(cell);cursor=cursor.plusDays(1);}}
    private void updateCalendarCell(LocalDate date){for(CalendarCell cell:calendarCells)if(date.equals(cell.date)){bindCalendarCell(cell);return;}}
    private void bindCalendarCell(CalendarCell cell){boolean inMonth=YearMonth.from(cell.date).equals(calendarMonth),selected=cell.date.equals(selectedDate);cell.day.setText(String.valueOf(cell.date.getDayOfMonth()));cell.day.setTextColor(selected?Color.WHITE:inMonth?INK:Color.rgb(190,195,206));long amount=dailyTotal(cell.date);cell.amount.setText(amount==0?"":shortMoney(amount));cell.amount.setTextColor(selected?Color.WHITE:MUTED);cell.root.setBackground(selected?round(BLUE,14):null);cell.root.setClickable(inMonth);}
    private void updateDayList(){List<Item> day=itemsForDate(selectedDate);dayTitle.setText(selectedDate.format(DateTimeFormatter.ofPattern("M월 d일 거래")));dayCount.setText(day.size()+"건");dayAdapter.submit(day);}
    private void onItemChanged(Item item){updateSummary();recentAdapter.refresh(item.id);dayAdapter.refresh(item.id);updateCalendarCell(Instant.ofEpochMilli(item.time).atZone(ZoneId.of("Asia/Seoul")).toLocalDate());categoryAdapter.refresh(item.id);}
    private void applyMerchantCategory(Item source,int category){
        Set<String> changedIds=new HashSet<>();android.content.SharedPreferences.Editor editor=saved.edit().putInt(MerchantNames.categoryKey(source.body),category);
        for(Item item:items)if(MerchantNames.same(source.body,item.body)){if(item.category!=category)changedIds.add(item.id);item.category=category;editor.putInt("category_"+item.id,category);}
        editor.apply();if(changedIds.isEmpty())return;updateSummary();recentAdapter.refresh(changedIds);dayAdapter.refresh(changedIds);List<Item> filtered=filteredItems();categoryCount.setText(filtered.size()+"건");categoryAdapter.submit(filtered);categoryAdapter.refresh(changedIds);toast(MerchantNames.extract(source.body)+" 내역 "+changedIds.size()+"건을 "+LABELS[category]+"으로 분류했습니다.");
    }

    private List<Item> filteredItems(){List<Item> result=new ArrayList<>();for(Item item:items)if(selectedCategory==-2||item.category==selectedCategory)result.add(item);return result;}
    private long[] totals(){long[] values=new long[7];for(Item item:items)if(item.amount!=null&&item.category>=0)values[item.category]+=SmsParser.signed(item.amount,item.cancelled);return values;}
    private List<Item> itemsForDate(LocalDate date){List<Item> result=new ArrayList<>();ZoneId zone=ZoneId.of("Asia/Seoul");for(Item item:items)if(Instant.ofEpochMilli(item.time).atZone(zone).toLocalDate().equals(date))result.add(item);return result;}
    private long dailyTotal(LocalDate date){long total=0;for(Item item:itemsForDate(date))if(item.amount!=null)total+=SmsParser.signed(item.amount,item.cancelled);return total;}

    private final class TransactionAdapter extends RecyclerView.Adapter<TransactionHolder>{
        private final boolean editable;private final List<Item> rows=new ArrayList<>();
        TransactionAdapter(boolean editable){this.editable=editable;setHasStableIds(true);}
        @Override public long getItemId(int position){return rows.get(position).id.hashCode();}
        @Override public TransactionHolder onCreateViewHolder(ViewGroup parent,int type){return new TransactionHolder(buildTransactionCard(editable));}
        @Override public void onBindViewHolder(TransactionHolder holder,int position){holder.bind(rows.get(position),editable);}
        @Override public int getItemCount(){return rows.size();}
        void submit(List<Item> next){List<Item> before=new ArrayList<>(rows),after=new ArrayList<>(next);DiffUtil.DiffResult diff=DiffUtil.calculateDiff(new DiffUtil.Callback(){public int getOldListSize(){return before.size();}public int getNewListSize(){return after.size();}public boolean areItemsTheSame(int o,int n){return before.get(o).id.equals(after.get(n).id);}public boolean areContentsTheSame(int o,int n){Item a=before.get(o),b=after.get(n);return a.time==b.time&&Objects.equals(a.amount,b.amount)&&a.cancelled==b.cancelled&&a.category==b.category&&Objects.equals(a.body,b.body);}});rows.clear();rows.addAll(after);diff.dispatchUpdatesTo(this);}
        void refresh(String id){for(int i=0;i<rows.size();i++)if(rows.get(i).id.equals(id)){notifyItemChanged(i);return;}}
        void refresh(Set<String> ids){for(int i=0;i<rows.size();i++)if(ids.contains(rows.get(i).id))notifyItemChanged(i);}
    }
    private static final class TransactionViews {TextView when,state,merchant,category,amount,edit;TextView[] chips=new TextView[7];}
    private final class TransactionHolder extends RecyclerView.ViewHolder{
        final TransactionViews v;TransactionHolder(View item){super(item);v=(TransactionViews)item.getTag();}
        void bind(Item item,boolean editable){v.when.setText(DateTimeFormatter.ofPattern("MM.dd  HH:mm").format(Instant.ofEpochMilli(item.time).atZone(ZoneId.of("Asia/Seoul"))));v.state.setText(item.cancelled?"취소":"승인");v.state.setTextColor(item.cancelled?Color.rgb(196,48,64):Color.rgb(26,134,89));v.state.setBackground(round(item.cancelled?Color.rgb(255,235,238):Color.rgb(230,248,239),50));v.merchant.setText(MerchantNames.extract(item.body));v.category.setText(item.category<0?"미분류":LABELS[item.category]);v.category.setTextColor(item.category<0?MUTED:BLUE);v.amount.setText(item.amount==null?"확인 필요":money(SmsParser.signed(item.amount,item.cancelled)));v.amount.setTextColor(item.cancelled?Color.rgb(196,48,64):NAVY);if(editable){for(int i=0;i<7;i++){final int index=i;v.chips[i].setTextColor(item.category==i?Color.WHITE:INK);v.chips[i].setBackground(round(item.category==i?BLUE:Color.rgb(241,243,247),50));v.chips[i].setOnClickListener(view->applyMerchantCategory(item,index));}v.edit.setOnClickListener(view->edit(item));}}
    }
    private View buildTransactionCard(boolean editable){LinearLayout card=card(dp(15),SURFACE,18);card.setElevation(dp(1));card.setLayoutParams(new RecyclerView.LayoutParams(-1,-2));TransactionViews v=new TransactionViews();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);card.addView(top);v.when=label("",11,true,MUTED);top.addView(v.when,new LinearLayout.LayoutParams(0,-2,1));v.state=label("",10,true,Color.rgb(26,134,89));v.state.setPadding(dp(8),dp(4),dp(8),dp(4));top.addView(v.state);LinearLayout info=new LinearLayout(this);info.setGravity(Gravity.CENTER_VERTICAL);card.addView(info,lp(-1,-2,0,dp(8),0,0));LinearLayout merchantBox=column();info.addView(merchantBox,new LinearLayout.LayoutParams(0,-2,1));v.merchant=label("",15,true,INK);merchantBox.addView(v.merchant);v.category=label("",11,true,MUTED);merchantBox.addView(v.category);v.amount=label("",19,true,NAVY);info.addView(v.amount);if(editable){View divider=new View(this);divider.setBackgroundColor(LINE);card.addView(divider,lp(-1,dp(1),0,dp(12),0,dp(8)));for(int first=0;first<7;first+=4){LinearLayout row=new LinearLayout(this);card.addView(row,lp(-1,-2,0,dp(5),0,0));for(int j=first;j<Math.min(first+4,7);j++){v.chips[j]=label(LABELS[j],11,true,INK);v.chips[j].setGravity(Gravity.CENTER);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(36),1);if(j>first)cp.setMargins(dp(6),0,0,0);row.addView(v.chips[j],cp);}}v.edit=label("금액·상태 수정",11,true,MUTED);v.edit.setGravity(Gravity.CENTER);v.edit.setPadding(0,dp(10),0,dp(2));card.addView(v.edit);}LinearLayout wrapper=column();wrapper.setPadding(0,dp(6),0,dp(6));wrapper.addView(card);wrapper.setTag(v);return wrapper;}

    private void pick(boolean first){LocalDate d=first?start:end;new DatePickerDialog(this,(p,y,m,day)->{if(first)start=LocalDate.of(y,m+1,day);else end=LocalDate.of(y,m+1,day);saved.edit().putString("ui_start",start.toString()).putString("ui_end",end.toString()).apply();selectedDate=end;calendarMonth=YearMonth.from(end);load();},d.getYear(),d.getMonthValue()-1,d.getDayOfMonth()).show();}
    private void startRcsImport(){saved.edit().putString("ui_start",start.toString()).putString("ui_end",end.toString()).apply();if(!RcsAccessibilityService.ready()){new AlertDialog.Builder(this).setTitle("RCS 불러오기 설정").setMessage("접근성 설정의 설치된 앱에서 ‘삼성카드 RCS 불러오기’를 켜 주세요. 선택한 기간의 삼성카드 대화만 읽으며 내역은 휴대폰에 저장됩니다.").setNegativeButton("나중에",null).setPositiveButton("설정 열기",(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_ACCESSIBILITY_SETTINGS))).show();return;}if(start.isAfter(LocalDate.now())){toast("시작일은 오늘 이후일 수 없습니다.");return;}RcsAccessibilityService.begin(start,end);}
    @Override public void onResume(){super.onResume();if(pager!=null)load();}
    private void edit(Item item){LinearLayout fields=column();fields.setPadding(dp(20),0,dp(20),0);EditText input=new EditText(this);input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);input.setHint("양수 원화 금액");if(item.amount!=null)input.setText(String.valueOf(item.amount));fields.addView(input);CheckBox cancelled=new CheckBox(this);cancelled.setText("취소 거래 (합계에서 차감)");cancelled.setChecked(item.cancelled);fields.addView(cancelled);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("거래 수정").setView(fields).setNegativeButton("닫기",null).setPositiveButton("저장",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{long value=Long.parseLong(input.getText().toString());if(value<0||value>1000000000000L)throw new NumberFormatException();item.amount=value;item.cancelled=cancelled.isChecked();saved.edit().putLong("amount_"+item.id,value).putBoolean("cancel_"+item.id,item.cancelled).apply();dialog.dismiss();onItemChanged(item);}catch(NumberFormatException e){input.setError("0~1조 원 사이의 정수를 입력하세요.");}}));dialog.show();}
    private String money(long value){return NumberFormat.getIntegerInstance(Locale.KOREA).format(value)+"원";}
    private String shortMoney(long value){long abs=Math.abs(value);if(abs>=10000)return(value<0?"-":"")+(abs/10000)+"만";return NumberFormat.getIntegerInstance(Locale.KOREA).format(value);}
    private Button dateButton(LocalDate date){Button b=new Button(this);b.setAllCaps(false);b.setText(date.format(DateTimeFormatter.ofPattern("yyyy.MM.dd")));b.setTextSize(16);b.setTypeface(null,Typeface.BOLD);b.setTextColor(INK);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setPadding(0,0,0,0);b.setMinHeight(0);b.setMinimumHeight(0);b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private LinearLayout dateCell(String title,Button button,int background,int accent){LinearLayout box=card(dp(13),background,14);box.addView(label(title,11,true,accent));box.addView(button,lp(-1,dp(38),0,dp(2),0,0));return box;}
    private TextView navArrow(String text){TextView v=label(text,28,false,NAVY);v.setGravity(Gravity.CENTER);v.setBackground(round(SURFACE,14));return v;}
    private LinearLayout sectionHeader(String title,String detail){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(label(title,18,true,NAVY),new LinearLayout.LayoutParams(0,-2,1));row.addView(label(detail,11,true,MUTED));return row;}
    private RecyclerView list(RecyclerView.Adapter<?> adapter){RecyclerView view=new RecyclerView(this);view.setLayoutManager(new LinearLayoutManager(this));view.setAdapter(adapter);view.setClipToPadding(false);view.setPadding(0,0,0,dp(12));view.setItemAnimator(null);return view;}
    private ScrollView scroller(){ScrollView s=new ScrollView(this);s.setClipToPadding(false);s.setPadding(0,0,0,dp(14));return s;}
    private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
    private LinearLayout card(int padding,int color,int radius){LinearLayout v=column();v.setPadding(padding,padding,padding,padding);v.setBackground(round(color,radius));return v;}
    private TextView label(String value,int size,boolean bold,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private LinearLayout.LayoutParams lp(int w,int h,int left,int top,int right,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(left,top,right,bottom);return p;}
    private int dp(int n){return(int)(getResources().getDisplayMetrics().density*n+.5f);}
    private void toast(String value){Toast.makeText(this,value,Toast.LENGTH_LONG).show();}
    @Override public void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("start",start.toString());state.putString("end",end.toString());state.putString("selectedDate",selectedDate.toString());state.putString("calendarMonth",calendarMonth.toString());state.putInt("category",selectedCategory);}
}
