package com.doyun.ledger;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.NumberFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class MainActivity extends Activity {
    private static final String[] LABELS={"외식","쇼핑","쿠팡","배달","기타","공과금","제외"};
    private static final String[] NAV={"▦  대시보드","≡  카테고리","□  캘린더"};
    private static final int NAVY=Color.rgb(24,35,58),BLUE=Color.rgb(48,94,255),INK=Color.rgb(31,41,55),MUTED=Color.rgb(107,114,128);
    private static final int SURFACE=Color.WHITE,BG=Color.rgb(246,247,251),LINE=Color.rgb(230,233,240);
    private final List<Item> items=new ArrayList<>();
    private final TextView[] navButtons=new TextView[3];
    private LocalDate start=LocalDate.now().withDayOfMonth(1),end=LocalDate.now(),selectedDate=LocalDate.now();
    private YearMonth calendarMonth=YearMonth.now();
    private android.content.SharedPreferences saved;
    private LinearLayout root;
    private SwipePager pager;
    private int selectedCategory=-2;

    static final class Item { long time;String id,body;Long amount;boolean cancelled;int category=-1; }

    @Override public void onCreate(Bundle state){
        super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(SURFACE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        saved=getSharedPreferences("labels",MODE_PRIVATE);start=LocalDate.parse(saved.getString("ui_start",start.toString()));end=LocalDate.parse(saved.getString("ui_end",end.toString()));selectedDate=end;calendarMonth=YearMonth.from(end);
        if(state!=null){start=LocalDate.parse(state.getString("start"));end=LocalDate.parse(state.getString("end"));selectedDate=LocalDate.parse(state.getString("selectedDate"));calendarMonth=YearMonth.parse(state.getString("calendarMonth"));}
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(18),0,dp(18),0);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(18),i.getSystemWindowInsetTop()+dp(12),dp(18),i.getSystemWindowInsetBottom());return i;});setContentView(root);
        addAppHeader();pager=new SwipePager(this);root.addView(pager,new LinearLayout.LayoutParams(-1,0,1));addBottomNav();pager.setListener(this::selectNav);load();
    }

    private void addAppHeader(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);root.addView(row,lp(-1,dp(58),0,0,0,dp(4)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);row.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView eyebrow=label("BOOBOO CARD",10,true,MUTED);eyebrow.setLetterSpacing(.13f);titles.addView(eyebrow);titles.addView(label("우리 카드 장부",23,true,NAVY),lp(-1,-2,0,dp(3),0,0));TextView privacy=label("LOCAL",10,true,Color.rgb(44,126,91));privacy.setPadding(dp(10),dp(6),dp(10),dp(6));privacy.setBackground(round(Color.rgb(229,247,239),50));row.addView(privacy);}
    private void addBottomNav(){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);bar.setPadding(dp(5),dp(7),dp(5),dp(4));bar.setBackground(round(SURFACE,20));bar.setElevation(dp(10));root.addView(bar,lp(-1,dp(66),0,dp(5),0,0));for(int i=0;i<3;i++){final int page=i;TextView tab=label(NAV[i],12,true,MUTED);tab.setGravity(Gravity.CENTER);tab.setClickable(true);tab.setOnClickListener(v->pager.showPage(page,page>pager.getDisplayedChild()));navButtons[i]=tab;bar.addView(tab,new LinearLayout.LayoutParams(0,-1,1));}selectNav(0);}
    private void selectNav(int page){for(int i=0;i<3;i++){navButtons[i].setTextColor(i==page?BLUE:MUTED);navButtons[i].setBackground(i==page?round(Color.rgb(237,242,255),14):null);}}

    private void load(){ZoneId zone=ZoneId.of("Asia/Seoul");long from=start.atStartOfDay(zone).toInstant().toEpochMilli(),until=end.plusDays(1).atStartOfDay(zone).toInstant().toEpochMilli();try(RcsStore store=new RcsStore(this)){items.clear();items.addAll(store.read(from,until,saved));}refreshPages();}
    private void refreshPages(){int current=pager.getChildCount()==0?0:pager.getDisplayedChild();pager.removeAllViews();pager.addView(dashboardPage());pager.addView(categoryPage());pager.addView(calendarPage());pager.setDisplayedChild(Math.min(current,2));selectNav(Math.min(current,2));}

    private View dashboardPage(){ScrollView scroll=scroller();LinearLayout page=column();scroll.addView(page);page.addView(periodCard(),lp(-1,-2,0,dp(6),0,dp(10)));page.addView(importButton(),lp(-1,dp(56),0,0,0,dp(10)));page.addView(statusCard(),lp(-1,-2,0,0,0,dp(10)));page.addView(summaryCard(),lp(-1,-2,0,0,0,dp(16)));page.addView(sectionHeader("최근 거래","카테고리 탭에서 전체보기"));int shown=Math.min(items.size(),4);if(shown==0)page.addView(emptyCard("아직 저장된 내역이 없어요\nRCS 내역을 먼저 불러오세요"),lp(-1,-2,0,dp(8),0,dp(12)));for(int i=0;i<shown;i++)page.addView(transactionCard(items.get(i),false),lp(-1,-2,0,dp(7),0,dp(7)));return scroll;}
    private View periodCard(){LinearLayout card=card(dp(17),SURFACE,20);card.addView(label("조회 기간",12,true,MUTED));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);card.addView(row,lp(-1,-2,0,dp(8),0,0));Button from=dateButton(start),to=dateButton(end);from.setOnClickListener(v->pick(true));to.setOnClickListener(v->pick(false));row.addView(dateCell("시작일",from),new LinearLayout.LayoutParams(0,-2,1));row.addView(new Space(this),new LinearLayout.LayoutParams(dp(9),1));row.addView(dateCell("종료일",to),new LinearLayout.LayoutParams(0,-2,1));return card;}
    private Button importButton(){Button button=new Button(this);button.setAllCaps(false);button.setText("삼성카드 RCS 불러오기  →");button.setTextSize(15);button.setTypeface(null,Typeface.BOLD);button.setTextColor(Color.WHITE);button.setBackground(round(BLUE,16));button.setElevation(dp(2));button.setOnClickListener(v->{if(start.isAfter(end)){toast("시작일은 종료일보다 늦을 수 없습니다.");return;}startRcsImport();});return button;}
    private View statusCard(){String result=getSharedPreferences("rcs_import",0).getString("status","불러오기를 누르면 삼성카드 대화에서 내역을 수집합니다.");LinearLayout card=card(dp(14),Color.rgb(237,242,255),15);TextView message=label("●   "+result+"\n     "+start+" ~ "+end+" · "+items.size()+"건",12,false,Color.rgb(55,71,112));message.setLineSpacing(0,1.2f);card.addView(message);return card;}
    private View summaryCard(){long[] totals=totals();long all=0;for(Item item:items)if(item.amount!=null)all+=SmsParser.signed(item.amount,item.cancelled);long actual=all-totals[6];LinearLayout card=card(dp(18),NAVY,22);card.setElevation(dp(2));card.addView(label("실제 카드값",12,true,Color.rgb(177,188,214)));card.addView(label(money(actual),29,true,Color.WHITE),lp(-1,-2,0,dp(3),0,0));card.addView(label("총 카드값 "+money(all)+" · 제외 "+money(totals[6])+" · "+items.size()+"건",11,false,Color.rgb(177,188,214)),lp(-1,-2,0,dp(2),0,dp(12)));LinearLayout data=new LinearLayout(this);data.setGravity(Gravity.CENTER_VERTICAL);card.addView(data);DonutChartView chart=new DonutChartView(this);chart.setValues(totals);data.addView(chart,new LinearLayout.LayoutParams(dp(130),dp(130)));LinearLayout legend=new LinearLayout(this);legend.setOrientation(LinearLayout.VERTICAL);legend.setPadding(dp(16),0,0,0);data.addView(legend,new LinearLayout.LayoutParams(0,-2,1));for(int i=0;i<7;i++){TextView line=label(LABELS[i]+"   "+money(totals[i]),11,i<3,Color.rgb(220,225,238));line.setPadding(0,dp(3),0,dp(3));legend.addView(line);}return card;}

    private View categoryPage(){LinearLayout page=column();page.addView(sectionHeader("카테고리별 내역",filteredItems().size()+"건"),lp(-1,-2,0,dp(6),0,dp(5)));HorizontalScrollView chipScroll=new HorizontalScrollView(this);chipScroll.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chipScroll.addView(chips);String[] filters={"전체","미분류","외식","쇼핑","쿠팡","배달","기타","공과금","제외"};for(int i=0;i<filters.length;i++){int value=i-2;TextView chip=label(filters[i],12,true,selectedCategory==value?Color.WHITE:INK);chip.setGravity(Gravity.CENTER);chip.setPadding(dp(15),0,dp(15),0);chip.setBackground(round(selectedCategory==value?BLUE:SURFACE,50));LinearLayout.LayoutParams cp=lp(-2,dp(38),0,0,dp(7),0);chips.addView(chip,cp);chip.setOnClickListener(v->{selectedCategory=value;refreshPages();});}page.addView(chipScroll,lp(-1,dp(42),0,0,0,dp(4)));ScrollView scroll=scroller();LinearLayout content=column();scroll.addView(content);List<Item> filtered=filteredItems();if(filtered.isEmpty())content.addView(emptyCard("이 분류에 저장된 거래가 없어요"),lp(-1,-2,0,dp(8),0,0));for(Item item:filtered)content.addView(transactionCard(item,true),lp(-1,-2,0,dp(7),0,dp(7)));page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return page;}
    private List<Item> filteredItems(){List<Item> result=new ArrayList<>();for(Item item:items)if(selectedCategory==-2||item.category==selectedCategory)result.add(item);return result;}

    private View calendarPage(){LinearLayout page=column();LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);page.addView(heading,lp(-1,dp(52),0,dp(4),0,0));TextView prev=navArrow("‹"),next=navArrow("›");TextView month=label(calendarMonth.format(DateTimeFormatter.ofPattern("yyyy년 M월")),19,true,NAVY);month.setGravity(Gravity.CENTER);heading.addView(prev,lp(dp(44),dp(44),0,0,0,0));heading.addView(month,new LinearLayout.LayoutParams(0,-2,1));heading.addView(next,lp(dp(44),dp(44),0,0,0,0));prev.setOnClickListener(v->{calendarMonth=calendarMonth.minusMonths(1);selectedDate=calendarMonth.atDay(1);refreshPages();});next.setOnClickListener(v->{calendarMonth=calendarMonth.plusMonths(1);selectedDate=calendarMonth.atDay(1);refreshPages();});page.addView(calendarGrid(),lp(-1,-2,0,0,0,dp(10)));List<Item> day=itemsForDate(selectedDate);page.addView(sectionHeader(selectedDate.format(DateTimeFormatter.ofPattern("M월 d일 거래")),day.size()+"건"));ScrollView scroll=scroller();LinearLayout content=column();scroll.addView(content);if(day.isEmpty())content.addView(emptyCard("이 날짜에는 거래가 없어요"),lp(-1,-2,0,dp(8),0,0));for(Item item:day)content.addView(transactionCard(item,false),lp(-1,-2,0,dp(7),0,dp(7)));page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return page;}
    private View calendarGrid(){LinearLayout card=card(dp(12),SURFACE,20);String[] weekdays={"일","월","화","수","목","금","토"};LinearLayout names=new LinearLayout(this);for(int i=0;i<7;i++){TextView name=label(weekdays[i],11,true,i==0?Color.rgb(218,76,83):i==6?BLUE:MUTED);name.setGravity(Gravity.CENTER);names.addView(name,new LinearLayout.LayoutParams(0,dp(28),1));}card.addView(names);LocalDate first=calendarMonth.atDay(1);int offset=first.getDayOfWeek().getValue()%7;LocalDate cursor=first.minusDays(offset);for(int week=0;week<6;week++){LinearLayout row=new LinearLayout(this);card.addView(row);for(int d=0;d<7;d++){LocalDate date=cursor;boolean inMonth=YearMonth.from(date).equals(calendarMonth),selected=date.equals(selectedDate);long amount=dailyTotal(date);LinearLayout cell=new LinearLayout(this);cell.setOrientation(LinearLayout.VERTICAL);cell.setGravity(Gravity.CENTER);cell.setPadding(dp(2),dp(5),dp(2),dp(5));if(selected)cell.setBackground(round(BLUE,14));TextView day=label(String.valueOf(date.getDayOfMonth()),13,true,selected?Color.WHITE:inMonth?INK:Color.rgb(190,195,206));day.setGravity(Gravity.CENTER);cell.addView(day);TextView value=label(amount==0?"":shortMoney(amount),9,false,selected?Color.WHITE:MUTED);value.setGravity(Gravity.CENTER);value.setSingleLine();cell.addView(value,lp(-1,dp(18),0,dp(3),0,0));if(inMonth){cell.setClickable(true);cell.setOnClickListener(v->{selectedDate=date;refreshPages();});}row.addView(cell,new LinearLayout.LayoutParams(0,dp(58),1));cursor=cursor.plusDays(1);}}return card;}

    private View transactionCard(Item item,boolean editable){LinearLayout card=card(dp(15),SURFACE,18);card.setElevation(dp(1));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);card.addView(top);top.addView(label(DateTimeFormatter.ofPattern("MM.dd  HH:mm").format(Instant.ofEpochMilli(item.time).atZone(ZoneId.of("Asia/Seoul"))),11,true,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView state=label(item.cancelled?"취소":"승인",10,true,item.cancelled?Color.rgb(196,48,64):Color.rgb(26,134,89));state.setPadding(dp(8),dp(4),dp(8),dp(4));state.setBackground(round(item.cancelled?Color.rgb(255,235,238):Color.rgb(230,248,239),50));top.addView(state);LinearLayout info=new LinearLayout(this);info.setGravity(Gravity.CENTER_VERTICAL);card.addView(info,lp(-1,-2,0,dp(8),0,0));LinearLayout merchant=new LinearLayout(this);merchant.setOrientation(LinearLayout.VERTICAL);info.addView(merchant,new LinearLayout.LayoutParams(0,-2,1));merchant.addView(label(merchant(item.body),15,true,INK));merchant.addView(label(item.category<0?"미분류":LABELS[item.category],11,true,item.category<0?MUTED:BLUE));info.addView(label(item.amount==null?"확인 필요":money(SmsParser.signed(item.amount,item.cancelled)),19,true,item.cancelled?Color.rgb(196,48,64):NAVY));if(editable){View divider=new View(this);divider.setBackgroundColor(LINE);card.addView(divider,lp(-1,dp(1),0,dp(12),0,dp(8)));for(int first=0;first<7;first+=4){LinearLayout row=new LinearLayout(this);card.addView(row,lp(-1,-2,0,dp(5),0,0));for(int j=first;j<Math.min(first+4,7);j++){final int index=j;TextView chip=label(LABELS[j],11,true,item.category==j?Color.WHITE:INK);chip.setGravity(Gravity.CENTER);chip.setBackground(round(item.category==j?BLUE:Color.rgb(241,243,247),50));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(36),1);if(j>first)cp.setMargins(dp(6),0,0,0);row.addView(chip,cp);chip.setOnClickListener(v->{item.category=index;saved.edit().putInt("category_"+item.id,index).apply();refreshPages();});}}TextView edit=label("금액·상태 수정",11,true,MUTED);edit.setGravity(Gravity.CENTER);edit.setPadding(0,dp(10),0,dp(2));edit.setOnClickListener(v->edit(item));card.addView(edit);}return card;}

    private void pick(boolean first){LocalDate d=first?start:end;new DatePickerDialog(this,(p,y,m,day)->{if(first)start=LocalDate.of(y,m+1,day);else end=LocalDate.of(y,m+1,day);saved.edit().putString("ui_start",start.toString()).putString("ui_end",end.toString()).apply();selectedDate=end;calendarMonth=YearMonth.from(end);load();},d.getYear(),d.getMonthValue()-1,d.getDayOfMonth()).show();}
    private void startRcsImport(){saved.edit().putString("ui_start",start.toString()).putString("ui_end",end.toString()).apply();if(!RcsAccessibilityService.ready()){new AlertDialog.Builder(this).setTitle("RCS 불러오기 설정").setMessage("접근성 설정의 설치된 앱에서 ‘삼성카드 RCS 불러오기’를 켜 주세요. 선택한 기간의 삼성카드 대화만 읽으며 내역은 휴대폰에 저장됩니다.").setNegativeButton("나중에",null).setPositiveButton("설정 열기",(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_ACCESSIBILITY_SETTINGS))).show();return;}if(start.isAfter(LocalDate.now())){toast("시작일은 오늘 이후일 수 없습니다.");return;}RcsAccessibilityService.begin(start,end);}
    @Override public void onResume(){super.onResume();if(pager!=null)load();}
    private void edit(Item item){LinearLayout fields=column();fields.setPadding(dp(20),0,dp(20),0);EditText input=new EditText(this);input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);input.setHint("양수 원화 금액");if(item.amount!=null)input.setText(String.valueOf(item.amount));fields.addView(input);CheckBox cancelled=new CheckBox(this);cancelled.setText("취소 거래 (합계에서 차감)");cancelled.setChecked(item.cancelled);fields.addView(cancelled);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("거래 수정").setView(fields).setNegativeButton("닫기",null).setPositiveButton("저장",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{long value=Long.parseLong(input.getText().toString());if(value<0||value>1000000000000L)throw new NumberFormatException();item.amount=value;item.cancelled=cancelled.isChecked();saved.edit().putLong("amount_"+item.id,value).putBoolean("cancel_"+item.id,item.cancelled).apply();dialog.dismiss();refreshPages();}catch(NumberFormatException e){input.setError("0~1조 원 사이의 정수를 입력하세요.");}}));dialog.show();}

    private long[] totals(){long[] values=new long[7];for(Item item:items)if(item.amount!=null&&item.category>=0)values[item.category]+=SmsParser.signed(item.amount,item.cancelled);return values;}
    private List<Item> itemsForDate(LocalDate date){List<Item> result=new ArrayList<>();ZoneId zone=ZoneId.of("Asia/Seoul");for(Item item:items)if(Instant.ofEpochMilli(item.time).atZone(zone).toLocalDate().equals(date))result.add(item);return result;}
    private long dailyTotal(LocalDate date){long total=0;for(Item item:itemsForDate(date))if(item.amount!=null)total+=SmsParser.signed(item.amount,item.cancelled);return total;}
    private String merchant(String body){String[] lines=RcsParser.normalize(body).split("\n");if(lines.length>2){String value=lines[2].replaceFirst("^[0-9]{1,2}[/.-][0-9]{1,2}\\s+[0-9]{1,2}:[0-9]{2}\\s*","").trim();if(!value.isEmpty())return value;}return "삼성카드 이용내역";}
    private String money(long value){return NumberFormat.getIntegerInstance(Locale.KOREA).format(value)+"원";}
    private String shortMoney(long value){long abs=Math.abs(value);if(abs>=10000)return(value<0?"-":"")+(abs/10000)+"만";return NumberFormat.getIntegerInstance(Locale.KOREA).format(value);}
    private Button dateButton(LocalDate date){Button b=new Button(this);b.setAllCaps(false);b.setText(date.format(DateTimeFormatter.ofPattern("yyyy.MM.dd")));b.setTextSize(13);b.setTypeface(null,Typeface.BOLD);b.setTextColor(INK);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setPadding(0,0,0,0);b.setMinHeight(0);b.setMinimumHeight(0);b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private LinearLayout dateCell(String title,Button button){LinearLayout box=card(dp(11),Color.rgb(248,249,252),14);box.addView(label(title,10,true,MUTED));box.addView(button,lp(-1,dp(34),0,dp(1),0,0));return box;}
    private TextView navArrow(String text){TextView v=label(text,28,false,NAVY);v.setGravity(Gravity.CENTER);v.setBackground(round(SURFACE,14));return v;}
    private LinearLayout sectionHeader(String title,String detail){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(label(title,18,true,NAVY),new LinearLayout.LayoutParams(0,-2,1));row.addView(label(detail,11,true,MUTED));return row;}
    private LinearLayout emptyCard(String text){LinearLayout card=card(dp(26),SURFACE,18);TextView message=label("◎\n\n"+text,13,false,MUTED);message.setGravity(Gravity.CENTER);message.setLineSpacing(0,1.25f);card.addView(message);return card;}
    private ScrollView scroller(){ScrollView s=new ScrollView(this);s.setClipToPadding(false);s.setPadding(0,0,0,dp(14));return s;}
    private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
    private LinearLayout card(int padding,int color,int radius){LinearLayout v=column();v.setPadding(padding,padding,padding,padding);v.setBackground(round(color,radius));return v;}
    private TextView label(String value,int size,boolean bold,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private LinearLayout.LayoutParams lp(int w,int h,int left,int top,int right,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(left,top,right,bottom);return p;}
    private int dp(int n){return(int)(getResources().getDisplayMetrics().density*n+.5f);}
    private void toast(String value){Toast.makeText(this,value,Toast.LENGTH_LONG).show();}
    @Override public void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("start",start.toString());state.putString("end",end.toString());state.putString("selectedDate",selectedDate.toString());state.putString("calendarMonth",calendarMonth.toString());}
}
